export const ERR_TOO_MANY_REDIRECTS = 'net::ERR_TOO_MANY_REDIRECTS'

export const POST_ANALYSIS_ERRORS = {
  INVALID_DATETIME: 'INVALID_DATETIME',
  NULL_LOCATION: 'NULL_LOCATION',
  NULL_DATETIME: 'NULL_DATETIME',
  INVALID_LINE_FORMAT: 'INVALID_LINE_FORMAT',
  PAST_DATETIME: 'PAST_DATETIME',
}
